apiVersion: eventing.knative.dev/v1alpha1
kind: ClusterChannelProvisioner
metadata:
  name: kafka
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-channel-controller
  namespace: knative-eventing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-channel-controller
rules:
- apiGroups:
  - eventing.knative.dev
  resources:
  - channels
  - channels/status
  - clusterchannelprovisioners
  - clusterchannelprovisioners/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - eventing.knative.dev
  resources:
  - channels/finalizers
  - clusterchannelprovisioners/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - update
- apiGroups:
  - ""
  resourceNames:
  - kafka-channel-dispatcher
  resources:
  - configmaps
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-channel-controller-manage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafka-channel-controller
subjects:
- kind: ServiceAccount
  name: kafka-channel-controller
  namespace: knative-eventing
---
apiVersion: v1
data:
  bootstrapServers: REPLACE_WITH_CLUSTER_URL
kind: ConfigMap
metadata:
  name: kafka-channel-controller-config
  namespace: knative-eventing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-channel-controller
  namespace: knative-eventing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-channel-controller
  template:
    metadata:
      labels:
        app: kafka-channel-controller
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/knative-releases/github.com/knative/eventing/contrib/kafka/cmd/controller@sha256:4200310008b6059666d4610b7b38847d182c28ec36847776b508ad29a9680b8b
        name: kafka-channel-controller-controller
        volumeMounts:
        - mountPath: /etc/config-provisioner
          name: kafka-channel-controller-config
      serviceAccountName: kafka-channel-controller
      volumes:
      - configMap:
          name: kafka-channel-controller-config
        name: kafka-channel-controller-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-channel-dispatcher
  namespace: knative-eventing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-channel-dispatcher
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eventing.knative.dev
  resources:
  - channels
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-channel-dispatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafka-channel-dispatcher
subjects:
- kind: ServiceAccount
  name: kafka-channel-dispatcher
  namespace: knative-eventing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-channel-dispatcher
  namespace: knative-eventing
spec:
  replicas: 1
  selector:
    matchLabels:
      clusterChannelProvisioner: kafka
      role: dispatcher
  template:
    metadata:
      labels:
        clusterChannelProvisioner: kafka
        role: dispatcher
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/knative-releases/github.com/knative/eventing/contrib/kafka/cmd/dispatcher@sha256:832bb86d9bbeb3c95abff6d384d6409e0cffac11e00c5cae8326789c317c79ac
        name: dispatcher
        volumeMounts:
        - mountPath: /etc/config-provisioner
          name: kafka-channel-controller-config
      serviceAccountName: kafka-channel-dispatcher
      volumes:
      - configMap:
          name: kafka-channel-controller-config
        name: kafka-channel-controller-config

---
