apiVersion: v1
kind: Namespace
metadata:
  name: knative-sources

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-controller-manager
  namespace: knative-sources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventing-sources-kafka-controller
rules:
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - kafkasources
  - kafkasources/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - kafkasources/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - eventing.knative.dev
  resources:
  - eventtypes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-kafka-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventing-sources-kafka-controller
subjects:
- kind: ServiceAccount
  name: kafka-controller-manager
  namespace: knative-sources
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventing-sources-kafka-controller-addressable-resolver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver
subjects:
- kind: ServiceAccount
  name: kafka-controller-manager
  namespace: knative-sources

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  name: kafkasources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: KafkaSource
    plural: kafkasources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            bootstrapServers:
              minLength: 1
              type: string
            consumerGroup:
              minLength: 1
              type: string
            net:
              properties:
                sasl:
                  properties:
                    enable:
                      type: boolean
                    password:
                      properties:
                        secretKeyRef:
                          type: object
                      type: object
                    user:
                      properties:
                        secretKeyRef:
                          type: object
                      type: object
                  type: object
                tls:
                  properties:
                    caCert:
                      properties:
                        secretKeyRef:
                          type: object
                      type: object
                    cert:
                      properties:
                        secretKeyRef:
                          type: object
                      type: object
                    enable:
                      type: boolean
                    key:
                      properties:
                        secretKeyRef:
                          type: object
                      type: object
                  type: object
              type: object
            resources:
              properties:
                limits:
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
                requests:
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
              type: object
            serviceAccountName:
              type: string
            sink:
              type: object
            topics:
              minLength: 1
              type: string
          required:
          - bootstrapServers
          - topics
          - consumerGroup
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
            sinkUri:
              type: string
          type: object
  version: v1alpha1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kafka-controller-manager
  name: kafka-controller
  namespace: knative-sources
spec:
  ports:
  - port: 443
  selector:
    control-plane: kafka-controller-manager

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: kafka-controller-manager
  name: kafka-controller-manager
  namespace: knative-sources
spec:
  selector:
    matchLabels:
      control-plane: kafka-controller-manager
  serviceName: kafka-controller-manager
  template:
    metadata:
      labels:
        control-plane: kafka-controller-manager
    spec:
      containers:
      - env:
        - name: KAFKA_RA_IMAGE
          value: gcr.io/knative-releases/github.com/knative/eventing-contrib/kafka/source/cmd/receive_adapter@sha256:eafe18bbd659606f35a22d8b64389e91f48afff0f51782a9fabcbe84fa6637d0
        image: gcr.io/knative-releases/github.com/knative/eventing-contrib/kafka/source/cmd/controller@sha256:560df1756d7182c5b7b4b3684f35673f1c4650518db6f1d2bf63ecd383263ffd
        name: manager
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
        volumeMounts: null
      serviceAccount: kafka-controller-manager
      serviceAccountName: kafka-controller-manager
      terminationGracePeriodSeconds: 10

---
